steps:
- name: 'gcr.io/cloud-builders/pack'
  args: ["pack", "build", "ai-pokemon:$SHORT_SHA", "--builder", "gcr.io/buildpacks/builder"]

# Deploy container image to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'ai-back', 
          '--image', 'gcr.io/$PROJECT_ID/ai-pokemon:$SHORT_SHA', 
          '--region', 'southamerica-east1)', 
          '--platform', 'managed', 
          '--allow-unauthenticated']
